/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flashcards/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Due Flashcards */
        get: operations["get_due_flashcards_api_v1_flashcards_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flashcards/blitz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blitz Flashcards */
        get: operations["get_blitz_flashcards_api_v1_flashcards_blitz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flashcards/boss/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Boss Round */
        get: operations["get_boss_round_api_v1_flashcards_boss__topicId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flashcards/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Flashcard Review */
        post: operations["submit_flashcard_review_api_v1_flashcards_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_api_v1_quiz__topicId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/{quizId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz */
        post: operations["submit_quiz_api_v1_quiz__quizId__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Path */
        get: operations["get_progress_path_api_v1_progress_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Stats */
        get: operations["get_progress_stats_api_v1_progress_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Streak */
        get: operations["get_streak_api_v1_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streak/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use Streak Freeze */
        post: operations["use_streak_freeze_api_v1_streak_freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streak/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Streak */
        post: operations["recover_streak_api_v1_streak_recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curriculum/generate-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Cards */
        post: operations["generate_cards_api_v1_curriculum_generate_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FlashcardCardResponse */
        FlashcardCardResponse: {
            /** Id */
            id: string;
            /** Topicid */
            topicId: string;
            /** Topictitle */
            topicTitle: string;
            cardType: components["schemas"]["FlashcardCardType"];
            difficulty: components["schemas"]["FlashcardDifficulty"];
            /** Front */
            front: string;
            /** Back */
            back: string;
            /** Hint */
            hint?: string | null;
            /** Options */
            options?: components["schemas"]["FlashcardOptionResponse"][];
            /** Xpreward */
            xpReward: number;
            reviewState?: components["schemas"]["FlashcardReviewStateResponse"] | null;
        };
        /**
         * FlashcardCardType
         * @enum {string}
         */
        FlashcardCardType: "recall" | "mcq" | "fill_blank";
        /**
         * FlashcardDifficulty
         * @enum {string}
         */
        FlashcardDifficulty: "easy" | "medium" | "hard";
        /** FlashcardOptionResponse */
        FlashcardOptionResponse: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * FlashcardReviewRating
         * @enum {string}
         */
        FlashcardReviewRating: "forgot" | "hard" | "okay" | "easy";
        /** FlashcardReviewRequest */
        FlashcardReviewRequest: {
            /** Cardid */
            cardId: string;
            rating: components["schemas"]["FlashcardReviewRating"];
            /** Elapsedms */
            elapsedMs: number;
        };
        /** FlashcardReviewResponse */
        FlashcardReviewResponse: {
            /** Cardid */
            cardId: string;
            rating: components["schemas"]["FlashcardReviewRating"];
            /**
             * Nextreviewat
             * Format: date-time
             */
            nextReviewAt: string;
            /** Intervaldays */
            intervalDays: number;
            /** Celebrate */
            celebrate: boolean;
            /** Xpawarded */
            xpAwarded: number;
            /** Reviewscompletedthissession */
            reviewsCompletedThisSession?: number | null;
        };
        /** FlashcardReviewStateResponse */
        FlashcardReviewStateResponse: {
            /** Duenow */
            dueNow: boolean;
            /** Streakbonus */
            streakBonus: boolean;
            /** Ratingoptions */
            ratingOptions: components["schemas"]["FlashcardReviewRating"][];
        };
        /** FlashcardTopicSummaryResponse */
        FlashcardTopicSummaryResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Completed */
            completed: boolean;
        };
        /** FlashcardsBlitzResponse */
        FlashcardsBlitzResponse: {
            /** Topicid */
            topicId: string;
            /** Durationseconds */
            durationSeconds: number;
            /** Streakmultiplier */
            streakMultiplier: number;
            /** Cards */
            cards: components["schemas"]["FlashcardCardResponse"][];
        };
        /** FlashcardsBossResponse */
        FlashcardsBossResponse: {
            topic: components["schemas"]["FlashcardTopicSummaryResponse"];
            /** Passthreshold */
            passThreshold: number;
            /** Cards */
            cards: components["schemas"]["FlashcardCardResponse"][];
            /** Revisitconcepts */
            revisitConcepts: string[];
        };
        /** FlashcardsDueResponse */
        FlashcardsDueResponse: {
            /** Cards */
            cards: components["schemas"]["FlashcardCardResponse"][];
            /** Totaldue */
            totalDue: number;
            /** Sessionfocus */
            sessionFocus: string;
        };
        /** GenerateCardsRequest */
        GenerateCardsRequest: {
            /**
             * Topicid
             * Format: uuid
             */
            topicId: string;
            /** Topictitle */
            topicTitle: string;
            /** Cardcount */
            cardCount: number;
            difficulty: components["schemas"]["TopicDifficulty"];
            /** Notes */
            notes?: string | null;
        };
        /** GenerateCardsResponse */
        GenerateCardsResponse: {
            /**
             * Status
             * @constant
             */
            status: "accepted";
            /**
             * Topicid
             * Format: uuid
             */
            topicId: string;
            /** Requestedcount */
            requestedCount: number;
            /** Estimateddurationseconds */
            estimatedDurationSeconds: number;
            /** Adminpreview */
            adminPreview: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProgressPathResponse */
        ProgressPathResponse: {
            /** Topics */
            topics: components["schemas"]["ProgressTopicResponse"][];
            /** Currenttopicid */
            currentTopicId?: string | null;
        };
        /** ProgressStatsResponse */
        ProgressStatsResponse: {
            /** Currentstreak */
            currentStreak: number;
            /** Longeststreak */
            longestStreak: number;
            /** Cardsduetoday */
            cardsDueToday: number;
            /** Topics */
            topics: components["schemas"]["ProgressStatsTopicResponse"][];
        };
        /** ProgressStatsTopicResponse */
        ProgressStatsTopicResponse: {
            /** Topicid */
            topicId: string;
            /** Title */
            title: string;
            /** Masteryscore */
            masteryScore: number;
            status: components["schemas"]["TopicProgressStatus"];
        };
        /** ProgressTopicResponse */
        ProgressTopicResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Orderindex */
            orderIndex: number;
            difficulty: components["schemas"]["TopicDifficulty"];
            status: components["schemas"]["TopicProgressStatus"];
            /** Masteryscore */
            masteryScore: number;
            /** Laststudiedat */
            lastStudiedAt?: string | null;
        };
        /** QuizOptionResponse */
        QuizOptionResponse: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** QuizQuestionBreakdownResponse */
        QuizQuestionBreakdownResponse: {
            /** Questionid */
            questionId: string;
            /** Selectedoptionid */
            selectedOptionId: string;
            /** Correctoptionid */
            correctOptionId: string;
            /** Iscorrect */
            isCorrect: boolean;
            /** Explanation */
            explanation: string;
        };
        /** QuizQuestionResponse */
        QuizQuestionResponse: {
            /** Id */
            id: string;
            questionType: components["schemas"]["QuizQuestionType"];
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["QuizOptionResponse"][];
            /** Codesnippet */
            codeSnippet?: string | null;
            /** Hint */
            hint?: string | null;
        };
        /**
         * QuizQuestionType
         * @enum {string}
         */
        QuizQuestionType: "mcq" | "code_output" | "fill_blank";
        /** QuizResponse */
        QuizResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            topic: components["schemas"]["QuizTopicSummaryResponse"];
            /** Passthreshold */
            passThreshold: number;
            /** Questions */
            questions: components["schemas"]["QuizQuestionResponse"][];
        };
        /** QuizSubmitRequest */
        QuizSubmitRequest: {
            /** Answers */
            answers: {
                [key: string]: string;
            };
        };
        /** QuizSubmitResponse */
        QuizSubmitResponse: {
            /** Quizid */
            quizId: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Masterydelta */
            masteryDelta: number;
            /**
             * Recommendedaction
             * @enum {string}
             */
            recommendedAction: "unlock_next_topic" | "review_flashcards";
            /** Breakdown */
            breakdown: components["schemas"]["QuizQuestionBreakdownResponse"][];
        };
        /** QuizTopicSummaryResponse */
        QuizTopicSummaryResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Estimatedminutes */
            estimatedMinutes: number;
        };
        /** StreakActionResponse */
        StreakActionResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "freeze" | "recover";
            /** Message */
            message: string;
            streak: components["schemas"]["StreakResponse"];
        };
        /** StreakGraceWindowResponse */
        StreakGraceWindowResponse: {
            /** Active */
            active: boolean;
            /** Expiresat */
            expiresAt?: string | null;
            /** Misseddate */
            missedDate?: string | null;
        };
        /** StreakRageModalResponse */
        StreakRageModalResponse: {
            /** Show */
            show: boolean;
            /** Reason */
            reason: string;
            /** Cta */
            cta: string;
        };
        /** StreakRecoverRequest */
        StreakRecoverRequest: {
            /** Reviewscompleted */
            reviewsCompleted: number;
        };
        /** StreakRecoveryResponse */
        StreakRecoveryResponse: {
            /** Eligible */
            eligible: boolean;
            /**
             * Thresholdmet
             * @default false
             */
            thresholdMet: boolean;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /** Reviewsrequired */
            reviewsRequired: number;
            /** Reviewscompleted */
            reviewsCompleted: number;
            /** Reviewsremaining */
            reviewsRemaining: number;
        };
        /** StreakResponse */
        StreakResponse: {
            /** Currentstreak */
            currentStreak: number;
            /** Longeststreak */
            longestStreak: number;
            /** Freezetokensremaining */
            freezeTokensRemaining: number;
            /**
             * Freezeapplied
             * @default false
             */
            freezeApplied: boolean;
            /** Todaycompleted */
            todayCompleted: boolean;
            /** Lastactivitydate */
            lastActivityDate?: string | null;
            /** Protectedstreakdate */
            protectedStreakDate?: string | null;
            graceWindow: components["schemas"]["StreakGraceWindowResponse"];
            recovery: components["schemas"]["StreakRecoveryResponse"];
            rageModal: components["schemas"]["StreakRageModalResponse"];
            /** Weeklybar */
            weeklyBar: components["schemas"]["WeeklyBarDayResponse"][];
        };
        /**
         * TopicDifficulty
         * @enum {string}
         */
        TopicDifficulty: "beginner" | "intermediate" | "advanced";
        /**
         * TopicProgressStatus
         * @enum {string}
         */
        TopicProgressStatus: "locked" | "available" | "in_progress" | "completed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyBarDayResponse */
        WeeklyBarDayResponse: {
            /** Date */
            date: string;
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "done" | "today" | "warning" | "idle";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_due_flashcards_api_v1_flashcards_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardsDueResponse"];
                };
            };
        };
    };
    get_blitz_flashcards_api_v1_flashcards_blitz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardsBlitzResponse"];
                };
            };
        };
    };
    get_boss_round_api_v1_flashcards_boss__topicId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardsBossResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_flashcard_review_api_v1_flashcards_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashcardReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_api_v1_quiz__topicId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_api_v1_quiz__quizId__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_path_api_v1_progress_path_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressPathResponse"];
                };
            };
        };
    };
    get_progress_stats_api_v1_progress_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressStatsResponse"];
                };
            };
        };
    };
    get_streak_api_v1_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakResponse"];
                };
            };
        };
    };
    use_streak_freeze_api_v1_streak_freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakActionResponse"];
                };
            };
        };
    };
    recover_streak_api_v1_streak_recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreakRecoverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cards_api_v1_curriculum_generate_cards_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCardsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateCardsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
